services:
  postgres_db:
    image: postgres:16
    container_name: moyb_db
    restart: always
    environment:
      POSTGRES_USER: marten
      POSTGRES_PASSWORD: saluste
      POSTGRES_DB: moyb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  