<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { ANIMATION_CONFIG } from '@/config/animations';

const emit = defineEmits(['intro-complete']);
const isVisible = ref(true);
const isFadingOut = ref(false);

const closeIntro = () => {
  isFadingOut.value = true;
  setTimeout(() => {
    isVisible.value = false;
    emit('intro-complete');
  }, ANIMATION_CONFIG.intro.fadeOut.duration * 1000);
};

// Auto-close after display duration
onMounted(() => {
  setTimeout(closeIntro, ANIMATION_CONFIG.intro.displayDuration * 1000);
});
</script>


<template>
  <div v-if="isVisible" class="intro-overlay" :class="{ 'fade-out': isFadingOut }">
    <div class="intro-content">
      <p class="description">This webapp visualizes your workout on a musculature silhouette. Contains information generated by AI.</p>
      <h1 class="title">MOYB</h1>
      <p class="stats">Currently at 293 unique exercises, targeting 21 muscle groups of the human body.</p>
    </div>
  </div>
</template>

<style scoped>
/* ===== Base Layout ===== */
.intro-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999;
}

.intro-content {
  max-width: 650px;
  padding: 2rem;
  text-align: center;
}

/* ===== Colors & Backgrounds ===== */
.intro-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}

.intro-content {
  background: linear-gradient(to bottom, #D9D9D9, #FFFFFF);
  border: 5px solid;
  border-image: linear-gradient(to right, #F0F0F0, #FF4E88) 1;
  box-shadow: 0 0 60px 18px rgba(0, 0, 0, 0.25);
}

/* ===== Typography ===== */
.description, .title, .stats {
  font-family: 'Inter', sans-serif;
  color: black;
  line-height: 1.4;
}

.description {
  font-size: 22px;
  font-weight: 400;
  margin-bottom: -0.5rem;
  margin-top : 0;
}

.title {
  font-size: 50px;
  font-weight: 900;
  margin: 1.5rem 0;
  margin-left: 1.7rem;
  letter-spacing: 1.2em;
  text-align: center;
  width: 100%;
}

.stats {
  font-size: 22px;
  font-weight: 400;
  margin-top: -0.5rem;
}

/* ===== Animations ===== */
.intro-overlay {
  animation: fadeIn v-bind('ANIMATION_CONFIG.intro.fadeIn.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeIn.timing') forwards;
}

.fade-out {
  animation: fadeOut v-bind('ANIMATION_CONFIG.intro.fadeOut.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeOut.timing') forwards;
}

.intro-content {
  animation: contentFadeIn v-bind('ANIMATION_CONFIG.intro.fadeIn.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeIn.timing') forwards;
}

/* ===== Animation Keyframes ===== */
@keyframes fadeIn {
  0% {
    opacity: 0;
    backdrop-filter: blur(0);
  }
  100% {
    opacity: 1;
    backdrop-filter: blur(8px);
  }
}

@keyframes fadeOut {
  0% {
    opacity: 1;
    backdrop-filter: blur(8px);
  }
  100% {
    opacity: 0;
    backdrop-filter: blur(0);
  }
}

@keyframes contentFadeIn {
  0% {
    opacity: 0;
    transform: scale(0.95);
    filter: blur(8px);
  }
  100% {
    opacity: 1;
    transform: scale(1);
    filter: blur(0);
  }
}
</style>
