<script setup lang="ts">
import { ref } from 'vue';
import { ANIMATION_CONFIG } from '@/config/animations';

const emit = defineEmits<{
  'intro-complete': [useMobile: boolean]
}>();

const isVisible = ref(true);
const isFadingOut = ref(false);

const goToMobile = () => {
  isFadingOut.value = true;
  setTimeout(() => {
    isVisible.value = false;
    emit('intro-complete', true);
  }, ANIMATION_CONFIG.intro.fadeOut.duration * 1000);
};

const goToDesktop = () => {
  isFadingOut.value = true;
  setTimeout(() => {
    isVisible.value = false;
    emit('intro-complete', false);
  }, ANIMATION_CONFIG.intro.fadeOut.duration * 1000);
};
</script>

<template>
  <div v-if="isVisible" class="intro-overlay" :class="{ 'fade-out': isFadingOut }">
    <div class="intro-content">
      <p class="description">This webapp visualizes your workout on a musculature silhouette. Contains information generated by AI.</p>
      <h1 class="title">MOYB</h1>
      <p class="stats">Currently at 293 unique exercises, targeting 21 muscle groups of the human body.</p>
      <div class="button-container">
        <button class="mobile-button" @click="goToMobile">Mobile View</button>
        <button class="desktop-button" @click="goToDesktop">Desktop View</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
/* ===== Base Layout ===== */
.intro-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 9999;
}

.intro-content {
  max-width: 650px;
  padding: 2rem;
  text-align: center;
}

/* ===== Colors & Backgrounds ===== */
.intro-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}

.intro-content {
  background: linear-gradient(to bottom, #D9D9D9, #FFFFFF);
  border: 5px solid;
  border-image: linear-gradient(to right, #F0F0F0, #FF4E88) 1;
  box-shadow: 0 0 60px 18px rgba(0, 0, 0, 0.25);
}

/* ===== Typography ===== */
.description, .title, .stats {
  font-family: 'Inter', sans-serif;
  color: black;
  line-height: 1.4;
}

.description {
  font-size: 22px;
  font-weight: 400;
  margin-bottom: -0.5rem;
  margin-top : 0;
}

.title {
  font-size: 50px;
  font-weight: 900;
  margin: 1.5rem 0;
  margin-left: 1.7rem;
  letter-spacing: 1.2em;
  text-align: center;
  width: 100%;
}

.stats {
  font-size: 22px;
  font-weight: 400;
  margin-top: -0.5rem;
}

/* ===== Animations ===== */
.intro-overlay {
  animation: fadeIn v-bind('ANIMATION_CONFIG.intro.fadeIn.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeIn.timing') forwards;
}

.fade-out {
  animation: fadeOut v-bind('ANIMATION_CONFIG.intro.fadeOut.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeOut.timing') forwards;
}

.intro-content {
  animation: contentFadeIn v-bind('ANIMATION_CONFIG.intro.fadeIn.duration + "s"') v-bind('ANIMATION_CONFIG.intro.fadeIn.timing') forwards;
}

/* ===== Animation Keyframes ===== */
@keyframes fadeIn {
  0% {
    opacity: 0;
    backdrop-filter: blur(0);
  }
  100% {
    opacity: 1;
    backdrop-filter: blur(8px);
  }
}

@keyframes fadeOut {
  0% {
    opacity: 1;
    backdrop-filter: blur(8px);
  }
  100% {
    opacity: 0;
    backdrop-filter: blur(0);
  }
}

@keyframes contentFadeIn {
  0% {
    opacity: 0;
    transform: scale(0.95);
    filter: blur(8px);
  }
  100% {
    opacity: 1;
    transform: scale(1);
    filter: blur(0);
  }
}

/* ===== Button Styles ===== */
.button-container {
  display: flex;
  gap: 1rem;
  justify-content: center;
  margin-top: 2rem;
}

.mobile-button, .desktop-button {
  padding: 0.75rem 1.5rem;
  font-size: 16px;
  font-weight: 600;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s ease;
  font-family: 'Inter', sans-serif;
}

.mobile-button {
  background: linear-gradient(135deg, #FF4E88, #FF6B6B);
  color: white;
}

.mobile-button:hover {
  background: linear-gradient(135deg, #FF6B6B, #FF8E8E);
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(255, 78, 136, 0.3);
}

.desktop-button {
  background: linear-gradient(135deg, #4A90E2, #357ABD);
  color: white;
}

.desktop-button:hover {
  background: linear-gradient(135deg, #357ABD, #2E5F8A);
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(74, 144, 226, 0.3);
}
</style>
